In [57]:
# utwórz tablicę zawierającą 10 zer
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
#utwórz tablicę zawierającą 10 piątek
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [59]:
#utwórz tablicę zawierającą liczby od 10 do 50
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [60]:
#utwórz macierz (tablica wielowymiarowa) o wymiarach 3x3 zawierającą liczby od 0 do 8
np.arange(0,9,1).reshape([3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
#utwórz macierz jednostkową o wymiarach 3x3,
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
#utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej
np.random.normal(0,0.1,25).reshape([5,5])


array([[-0.14941195,  0.01581855,  0.06070116,  0.12262639, -0.10572168],
       [-0.06012094,  0.02421781, -0.15613478, -0.08754045, -0.05908965],
       [ 0.12187897, -0.05848711, -0.08778121, -0.03473394, -0.17558931],
       [-0.09609469, -0.05617356, -0.06553683,  0.05467376,  0.04338974],
       [ 0.12945504,  0.04010597, -0.22706424, -0.12152732, -0.033125  ]])

In [63]:
#utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01
np.arange(0.01,1.01,0.01).reshape([10,10])



array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [64]:
#utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1),
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [65]:
'''utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:
oblicz sumę wszystkich liczb w ww. macierzy,
oblicz średnią wszystkich liczb w ww. macierzy,
oblicz standardową dewiację dla liczb w ww. macierzy,
oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy.'''

array = np.random.uniform(1,25,25).reshape([5,5])
print("macierz: "+ str(array))
print("suma: " + str(np.sum(array)))
print("średnia: " + str(np.mean(array)))
print("dewiacja: " + str(np.std(array)))
col_sum = np.sum(array,axis=0)
print("suma kolumn: "+ str(col_sum))

macierz: [[ 4.47789754 24.69872747 18.86877029  2.80202578 19.70170414]
 [19.93427245  9.49957546 19.63850863 17.80770709 23.56123931]
 [14.92052497 23.98421393  7.86820025 13.53068399  8.96419243]
 [15.37377098  4.4376863  20.82514294 24.60256689  1.52712223]
 [21.71826767 16.37407858 12.92304692 10.42848366  6.11768593]]
suma: 364.58609582608943
średnia: 14.583443833043578
dewiacja: 7.167341833333357
suma kolumn: [76.42473361 78.99428174 80.12366903 69.17146741 59.87194404]


In [66]:
'''utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100) i:
oblicz medianę tych liczb,
znajdź najmniejszą liczbę tej macierzy,
znajdź największą liczbę tej macierzy.'''
array = np.random.uniform(0,100,25).reshape([5,5])
print(array)
print("mediana: " + str(np.median(array)))
print("najmniejsza liczba: "+ str(np.min(array)))
print("największa liczba: "+ str(np.max(array)))

[[37.51562526 77.50631079 93.05075662 27.57251201 68.06338005]
 [14.58237665 22.58545591 13.2288509  85.30895445 41.77014042]
 [52.41277484 27.3129647  92.28847428 87.20577056 27.93288829]
 [83.73481831 83.93028817 43.68796591 34.10559075 96.88626524]
 [25.49747258 52.91661597 79.48003353 93.18874799 57.48565957]]
mediana: 52.91661597445116
najmniejsza liczba: 13.228850902446599
największa liczba: 96.88626523900568


In [67]:
#utwórz macierz o wymiarach różnych od siebie i większych od 1, zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji
mat = np.random.uniform(0,100,24).reshape([6,4])
print(mat)
transposed = mat.T
print(transposed)

[[64.42171449 86.34792521  7.98966678 63.10973858]
 [64.64401739 20.56185922 29.3807026   3.09630833]
 [27.43412151 52.91331218 83.37370264 64.39563196]
 [13.18547121 22.3775812  66.47484508 45.09258862]
 [49.78515119 62.87000748 76.65421595 59.45098981]
 [45.98353959 88.74806448  0.70993913 41.37975303]]
[[64.42171449 64.64401739 27.43412151 13.18547121 49.78515119 45.98353959]
 [86.34792521 20.56185922 52.91331218 22.3775812  62.87000748 88.74806448]
 [ 7.98966678 29.3807026  83.37370264 66.47484508 76.65421595  0.70993913]
 [63.10973858  3.09630833 64.39563196 45.09258862 59.45098981 41.37975303]]


In [68]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać), większych od 2 i dodaj je do siebie
mat1 = np.random.uniform(0,100,25).reshape([5,5])
mat2 = np.random.uniform(0,100,25).reshape([5,5])
print(mat1, mat2,sep="\n\n")
print(mat1+mat2)

[[84.55427852 36.98424968  8.04799877 21.87298192 33.60466766]
 [93.0807775  30.23800591 76.43811456 46.69044073 27.9805185 ]
 [79.59829188 96.78157591 44.61651029 57.54633847 36.64951907]
 [ 4.67356481 64.80532531 89.76443122 62.92565762 98.0023565 ]
 [74.98677516 69.57842336 48.8933257  77.42158264 74.44094798]]

[[17.93911439 42.48237346 33.97945818 87.62493644 45.68282363]
 [84.78773125 49.00282666 94.90359042 39.97442991 86.70623907]
 [99.15440723 13.73483515  0.67473674 87.86897364 12.47168879]
 [26.53590846 19.69936829 94.23363568  9.99240878  1.2107695 ]
 [33.76772489 77.60047722 72.06804924 44.4623744   6.25198744]]
[[102.49339291  79.46662314  42.02745694 109.49791836  79.28749129]
 [177.86850875  79.24083257 171.34170498  86.66487064 114.68675757]
 [178.75269911 110.51641107  45.29124703 145.41531212  49.12120786]
 [ 31.20947326  84.5046936  183.9980669   72.9180664   99.213126  ]
 [108.75450005 147.17890057 120.96137493 121.88395704  80.69293543]]


In [69]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać) różnych od siebie i większych od 2, a następnie pomnóż je przez siebie za pomocą dwóch różnych funkcji (np. ‘matmul’ i ‘multiply’)
mat1 = np.random.uniform(0,100,6).reshape([2,3])
mat2 = np.random.uniform(0,100,6).reshape([3,2])
print(mat1, mat2,sep="\n\n")
print(np.matmul(mat1,mat2))

[[74.59468081 16.47660657 89.60711444]
 [49.1332497  81.46634347 17.75636857]]

[[11.31818784 44.26758626]
 [82.84729778  2.46621783]
 [44.33115182 37.67821932]]
[[6181.7055348  6718.9978793 ]
 [8092.52603705 3044.95246778]]
